In [1]:

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.model_selection import train_test_split, GridSearchCV, KFold
from sklearn.pipeline import Pipeline

In [2]:
#数据加载
df=pd.read_excel(r"C:\Users\yaoyao tang\Desktop\ML-hydrothermal\experiment_dataset.xlsx")
df.head()

邻苯二胺  酪氨酸  浓度  体积   温度  时间   Ex  Em1  Em2    QY
0   0.6  0.4   2  15  200  10  562  624  676  15.5
1   0.8  0.8   4  15  140  12  562  630  678  15.0
2   1.0  1.0   2  15  140  10  562  626  678  19.3
3   0.8  0.8   2  10  180   4  562  624  678  14.6
4   1.0  1.0   6  15  160  12  562  630  678  14.5

In [3]:
df.columns = ['M1','M2','C','V', 'T', 'H', 'Ex', 'Em1','Em2','QY']
df.head()

M1   M2  C   V    T   H   Ex  Em1  Em2    QY
0  0.6  0.4  2  15  200  10  562  624  676  15.5
1  0.8  0.8  4  15  140  12  562  630  678  15.0
2  1.0  1.0  2  15  140  10  562  626  678  19.3
3  0.8  0.8  2  10  180   4  562  624  678  14.6
4  1.0  1.0  6  15  160  12  562  630  678  14.5

In [4]:
x=np.array(df.loc[:,"M1":"H"])
y=np.array(df.loc[:,"QY"])

In [5]:
print(x.shape)
print(y.shape)

(216, 6)
(216,)


In [6]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from math import sqrt
def test(y_pred,y_true):
    r2=r2_score(y_true,y_pred)
    rmse=sqrt(mean_squared_error(y_pred,y_true))
    mae=mean_absolute_error(y_pred,y_true)
    return np.array([r2,rmse,mae])

In [7]:
import pandas as pd
import numpy as np
from xgboost.sklearn import XGBRegressor #XGB

from sklearn.model_selection import GridSearchCV, StratifiedKFold,train_test_split
from sklearn import metrics 

#handle warnings
import warnings
warnings.filterwarnings("ignore")

In [9]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2)

In [11]:
cv_params = {'n_estimators': [40,50,60,70,80,90,100,110,120]}

other_params = {'learning_rate': 0.1, 'n_estimators': 500, 'max_depth': 5, 'min_child_weight': 1, 'seed': 0,
                    'subsample': 0.8, 'colsample_bytree': 0.8, 'gamma': 0, 'reg_alpha': 0, 'reg_lambda': 1}

model = XGBRegressor(**other_params)
xgb_cv = GridSearchCV(estimator=model, param_grid=cv_params, scoring='r2', cv=5, verbose=1, n_jobs=4)
xgb_cv.fit(x_train, y_train)
print('参数的最佳取值：{0}'.format(xgb_cv.best_params_))
print('最佳模型得分:{0}'.format(xgb_cv.best_score_))
print("测试集得分:{0}".format(xgb_cv.score(x_test,y_test)))
print(test(xgb_cv.predict(x),y))

Fitting 5 folds for each of 9 candidates, totalling 45 fits
参数的最佳取值：{'n_estimators': 110}
最佳模型得分:0.7362348903540188
测试集得分:0.8165838506797424
[0.95292451 1.2973484  0.74163661]


In [12]:
cv_params = { 'max_depth': [1,2,3, 4,5,6,7,8,9], 'min_child_weight': [1, 2, 3, 4,5,6,7,8,9]}

other_params = {'learning_rate': 0.1, 'n_estimators': 110, 'max_depth': 5, 'min_child_weight': 1, 'seed': 0,
                    'subsample': 0.8, 'colsample_bytree': 0.8, 'gamma': 0, 'reg_alpha': 0, 'reg_lambda': 1}

model = XGBRegressor(**other_params)
xgb_cv = GridSearchCV(estimator=model, param_grid=cv_params, scoring='r2', cv=5, verbose=1, n_jobs=4)
xgb_cv.fit(x_train, y_train)
print('参数的最佳取值：{0}'.format(xgb_cv.best_params_))
print('最佳模型得分:{0}'.format(xgb_cv.best_score_))
print("测试集得分:{0}".format(xgb_cv.score(x_test,y_test)))
print(test(xgb_cv.predict(x_test),y_test))

Fitting 5 folds for each of 81 candidates, totalling 405 fits
参数的最佳取值：{'max_depth': 4, 'min_child_weight': 2}
最佳模型得分:0.7743411388913414
测试集得分:0.8417736377639693
[0.84177364 2.46986905 1.87433924]


In [13]:
cv_params = { 'gamma': [0.0001,0.001,0.01,0.05,0.08,0.1,0.15, 0.2, 0.3]}

other_params = {'learning_rate': 0.1, 'n_estimators': 110, 'max_depth': 4, 'min_child_weight': 2, 'seed': 0,
                    'subsample': 0.8, 'colsample_bytree': 0.8, 'gamma': 0, 'reg_alpha': 0, 'reg_lambda': 1}

model = XGBRegressor(**other_params)
xgb_cv = GridSearchCV(estimator=model, param_grid=cv_params, scoring='r2', cv=5, verbose=1, n_jobs=4)
xgb_cv.fit(x_train, y_train)
print('参数的最佳取值：{0}'.format(xgb_cv.best_params_))
print('最佳模型得分:{0}'.format(xgb_cv.best_score_))
print("测试集得分:{0}".format(xgb_cv.score(x_test,y_test)))
print(test(xgb_cv.predict(x_test),y_test))

Fitting 5 folds for each of 9 candidates, totalling 45 fits
参数的最佳取值：{'gamma': 0.15}
最佳模型得分:0.776406933871695
测试集得分:0.83711785823869
[0.83711786 2.50594331 1.86855809]


In [14]:
cv_params = { 'subsample': [0.4,0.5,0.6,0.7,0.8,0.9,1], 
             'colsample_bytree': [0.4,0.5,0.6,0.7,0.8,0.9,1]}

other_params = {'learning_rate': 0.1, 'n_estimators': 110, 'max_depth': 4, 'min_child_weight': 2, 'seed': 0,
                    'subsample': 0.8, 'colsample_bytree': 0.8, 'gamma': 0.15, 'reg_alpha': 0, 'reg_lambda': 1}

model = XGBRegressor(**other_params)
xgb_cv = GridSearchCV(estimator=model, param_grid=cv_params, scoring='r2', cv=5, verbose=1, n_jobs=4)
xgb_cv.fit(x_train, y_train)
print('参数的最佳取值：{0}'.format(xgb_cv.best_params_))
print('最佳模型得分:{0}'.format(xgb_cv.best_score_))
print("测试集得分:{0}".format(xgb_cv.score(x_test,y_test)))
print(test(xgb_cv.predict(x_test),y_test))

Fitting 5 folds for each of 49 candidates, totalling 245 fits
参数的最佳取值：{'colsample_bytree': 0.9, 'subsample': 0.9}
最佳模型得分:0.802149018282282
测试集得分:0.8416076427060772
[0.84160764 2.47116428 1.76753808]


In [15]:
cv_params = { 'reg_alpha': [0.05,0.01, 0.1, 1], 'reg_lambda': [0.05,0.01, 0.1, 1,5,10]}

other_params = {'learning_rate': 0.1, 'n_estimators': 110, 'max_depth': 4, 'min_child_weight': 2, 'seed': 0,
                    'subsample': 0.9, 'colsample_bytree': 0.9, 'gamma': 0.15, 'reg_alpha': 0, 'reg_lambda': 1}

model = XGBRegressor(**other_params)
xgb_cv = GridSearchCV(estimator=model, param_grid=cv_params, scoring='r2', cv=5, verbose=1, n_jobs=4)
xgb_cv.fit(x_train, y_train)
print('参数的最佳取值：{0}'.format(xgb_cv.best_params_))
print('最佳模型得分:{0}'.format(xgb_cv.best_score_))
print("测试集得分:{0}".format(xgb_cv.score(x_test,y_test)))
print(test(xgb_cv.predict(x_test),y_test))

Fitting 5 folds for each of 24 candidates, totalling 120 fits
参数的最佳取值：{'reg_alpha': 0.05, 'reg_lambda': 1}
最佳模型得分:0.8066532418557395
测试集得分:0.8404939296417173
[0.84049393 2.47983688 1.77829998]


In [16]:
cv_params = {  'learning_rate': [0.001, 0.01, 0.05, 0.07, 0.1,0.3,0.5,1]}

other_params = {'learning_rate': 0.1, 'n_estimators': 110, 'max_depth': 4, 'min_child_weight': 2, 'seed': 0,
                    'subsample': 0.9, 'colsample_bytree': 0.9, 'gamma': 0.15, 'reg_alpha': 0.05, 'reg_lambda': 1}

model = XGBRegressor(**other_params)
xgb_cv = GridSearchCV(estimator=model, param_grid=cv_params, scoring='r2', cv=5, verbose=1, n_jobs=4)
xgb_cv.fit(x_train, y_train)
print('参数的最佳取值：{0}'.format(xgb_cv.best_params_))
print('最佳模型得分:{0}'.format(xgb_cv.best_score_))
print("测试集得分:{0}".format(xgb_cv.score(x_test,y_test)))
print(test(xgb_cv.predict(x_test),y_test))

Fitting 5 folds for each of 8 candidates, totalling 40 fits
参数的最佳取值：{'learning_rate': 0.1}
最佳模型得分:0.8066532418557395
测试集得分:0.8404939296417173
[0.84049393 2.47983688 1.77829998]


In [17]:
other_params = {'learning_rate': 0.1, 'n_estimators': 110, 'max_depth': 4, 'min_child_weight': 2, 'seed': 0,
                    'subsample': 0.9, 'colsample_bytree': 0.9, 'gamma': 0.15, 'reg_alpha': 0.05, 'reg_lambda': 1}
model = XGBRegressor(**other_params)
model.fit(x, y)
print('模型得分:{0}'.format(model.score(x,y)))
print("测试集得分:{0}".format(model.score(x_test,y_test)))

模型得分:0.9728154770226612
测试集得分:0.976685683650509


##通过网格搜索确定模型的超参数，将全部的数据用于训练模型并且保存模型参数


In [18]:
other_params = {'learning_rate': 0.1, 'n_estimators': 80, 'max_depth': 4, 'min_child_weight': 6, 'seed': 0,
                    'subsample': 0.8, 'colsample_bytree': 0.7, 'gamma': 0.15, 'reg_alpha': 0.05, 'reg_lambda':0.1 }
model = XGBRegressor(**other_params)
model.fit(x, y)
model.score(x,y)

0.9548216694607896

In [29]:
#模型保存为model和txt两种格式
def model_save_type(model):
    # 模型训练完成后做持久化，模型保存为model模式，便于调用预测
    model.save_model('./model_save/xgb_regression.json')

    # 模型保存为文本格式，便于分析、优化和提供可解释性
    res = model.get_booster()
    res.dump_model('./model_save/xgb_regression.txt')
